-- Extensión requerida por la restricción de exclusión de acuerdo_precio (V005).
CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE empresa (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rut              VARCHAR(12)  NOT NULL,
  razon_social     VARCHAR(200) NOT NULL,
  nombre_fantasia  VARCHAR(200),
  activa           BOOLEAN NOT NULL DEFAULT TRUE,
  creado_por       VARCHAR(120) NOT NULL,
  creado_en        TIMESTAMPTZ  NOT NULL DEFAULT now(),
  modificado_por   VARCHAR(120),
  modificado_en    TIMESTAMPTZ,
  CONSTRAINT uq_empresa_rut UNIQUE (rut)
);

CREATE TABLE usuario (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id     BIGINT NOT NULL REFERENCES empresa(id),
  sub_oidc       VARCHAR(100) NOT NULL,
  email          VARCHAR(150) NOT NULL,
  nombre         VARCHAR(150) NOT NULL,
  rol            VARCHAR(20)  NOT NULL,
  activo         BOOLEAN NOT NULL DEFAULT TRUE,
  creado_por     VARCHAR(120) NOT NULL,
  creado_en      TIMESTAMPTZ  NOT NULL DEFAULT now(),
  modificado_por VARCHAR(120),
  modificado_en  TIMESTAMPTZ,
  CONSTRAINT uq_usuario_sub UNIQUE (sub_oidc),
  CONSTRAINT ck_usuario_rol CHECK (rol IN ('ADMINISTRADOR','OPERADOR'))
);

CREATE TABLE parametro_sistema (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id     BIGINT NOT NULL REFERENCES empresa(id),
  clave          VARCHAR(60)  NOT NULL,
  valor          VARCHAR(200) NOT NULL,
  descripcion    VARCHAR(300),
  creado_por     VARCHAR(120) NOT NULL,
  creado_en      TIMESTAMPTZ  NOT NULL DEFAULT now(),
  modificado_por VARCHAR(120),
  modificado_en  TIMESTAMPTZ,
  CONSTRAINT uq_parametro UNIQUE (empresa_id, clave)
);
