CREATE TABLE tipo_servicio (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id     BIGINT NOT NULL REFERENCES empresa(id),
  nombre         VARCHAR(120) NOT NULL,
  activo         BOOLEAN NOT NULL DEFAULT TRUE,
  creado_por     VARCHAR(120) NOT NULL,
  creado_en      TIMESTAMPTZ  NOT NULL DEFAULT now(),
  modificado_por VARCHAR(120),
  modificado_en  TIMESTAMPTZ,
  CONSTRAINT uq_tipo_servicio UNIQUE (empresa_id, nombre)
);
