CREATE TABLE cliente (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id      BIGINT NOT NULL REFERENCES empresa(id),
  rut             VARCHAR(12)  NOT NULL,
  razon_social    VARCHAR(200) NOT NULL,
  nombre_fantasia VARCHAR(200),
  giro            VARCHAR(150),
  email           VARCHAR(150),
  telefono        VARCHAR(30),
  direccion       VARCHAR(250),
  activo          BOOLEAN NOT NULL DEFAULT TRUE,
  creado_por      VARCHAR(120) NOT NULL,
  creado_en       TIMESTAMPTZ  NOT NULL DEFAULT now(),
  modificado_por  VARCHAR(120),
  modificado_en   TIMESTAMPTZ,
  CONSTRAINT uq_cliente_rut UNIQUE (empresa_id, rut)
);
