CREATE TABLE proyecto (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id       BIGINT NOT NULL REFERENCES empresa(id),
  cliente_id       BIGINT NOT NULL REFERENCES cliente(id),
  tipo_servicio_id BIGINT REFERENCES tipo_servicio(id),
  codigo           VARCHAR(40),
  nombre           VARCHAR(200) NOT NULL,
  descripcion      VARCHAR(500),
  precio_base_neto NUMERIC(18,4) NOT NULL,
  moneda_precio    VARCHAR(3)    NOT NULL,
  periodicidad     VARCHAR(10)   NOT NULL,
  dia_facturacion  SMALLINT      NOT NULL,
  fecha_inicio     DATE          NOT NULL,
  fecha_termino    DATE,
  activo           BOOLEAN NOT NULL DEFAULT TRUE,
  creado_por       VARCHAR(120) NOT NULL,
  creado_en        TIMESTAMPTZ  NOT NULL DEFAULT now(),
  modificado_por   VARCHAR(120),
  modificado_en    TIMESTAMPTZ,
  CONSTRAINT ck_proyecto_moneda       CHECK (moneda_precio IN ('UF','CLP')),
  CONSTRAINT ck_proyecto_periodicidad CHECK (periodicidad IN ('MENSUAL','ANUAL')),
  CONSTRAINT ck_proyecto_dia          CHECK (dia_facturacion BETWEEN 1 AND 31),
  CONSTRAINT ck_proyecto_precio       CHECK (precio_base_neto >= 0)
);
CREATE INDEX ix_proyecto_cliente ON proyecto (empresa_id, cliente_id);
CREATE INDEX ix_proyecto_activo  ON proyecto (empresa_id, activo);
