CREATE TABLE acuerdo_precio (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id     BIGINT NOT NULL REFERENCES empresa(id),
  proyecto_id    BIGINT NOT NULL REFERENCES proyecto(id),
  tipo           VARCHAR(25)   NOT NULL,
  valor          NUMERIC(18,4) NOT NULL,
  moneda         VARCHAR(3),
  fecha_inicio   DATE NOT NULL,
  fecha_termino  DATE NOT NULL,
  meses_pactados SMALLINT,
  observacion    VARCHAR(300),
  creado_por     VARCHAR(120) NOT NULL,
  creado_en      TIMESTAMPTZ  NOT NULL DEFAULT now(),
  modificado_por VARCHAR(120),
  modificado_en  TIMESTAMPTZ,
  CONSTRAINT ck_acuerdo_tipo CHECK (tipo IN ('DESCUENTO_PORCENTAJE','DESCUENTO_MONTO','PRECIO_PACTADO')),
  CONSTRAINT ck_acuerdo_moneda CHECK (
       (tipo = 'DESCUENTO_PORCENTAJE' AND moneda IS NULL)
    OR (tipo IN ('DESCUENTO_MONTO','PRECIO_PACTADO') AND moneda IN ('UF','CLP'))
  ),
  CONSTRAINT ck_acuerdo_porcentaje CHECK (
    tipo <> 'DESCUENTO_PORCENTAJE' OR (valor > 0 AND valor <= 100)
  ),
  CONSTRAINT ck_acuerdo_vigencia CHECK (fecha_termino >= fecha_inicio),
  CONSTRAINT ex_acuerdo_no_traslape EXCLUDE USING gist (
    proyecto_id WITH =,
    daterange(fecha_inicio, fecha_termino, '[]') WITH &&
  )
);
