CREATE TABLE archivo (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id      BIGINT NOT NULL REFERENCES empresa(id),
  nombre_original VARCHAR(255) NOT NULL,
  clave_objeto    VARCHAR(500) NOT NULL,
  tipo_contenido  VARCHAR(100) NOT NULL,
  tamano_bytes    BIGINT       NOT NULL,
  creado_por      VARCHAR(120) NOT NULL,
  creado_en       TIMESTAMPTZ  NOT NULL DEFAULT now(),
  modificado_por  VARCHAR(120),
  modificado_en   TIMESTAMPTZ,
  CONSTRAINT uq_archivo_clave UNIQUE (clave_objeto)
);

CREATE TABLE factura (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id     BIGINT NOT NULL REFERENCES empresa(id),
  numero_factura VARCHAR(40) NOT NULL,
  fecha_factura  DATE        NOT NULL,
  archivo_id     BIGINT REFERENCES archivo(id),
  observacion    VARCHAR(300),
  creado_por     VARCHAR(120) NOT NULL,
  creado_en      TIMESTAMPTZ  NOT NULL DEFAULT now(),
  modificado_por VARCHAR(120),
  modificado_en  TIMESTAMPTZ,
  CONSTRAINT uq_factura_numero UNIQUE (empresa_id, numero_factura)
);
