CREATE TABLE importacion_csv (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id        BIGINT NOT NULL REFERENCES empresa(id),
  archivo_id        BIGINT REFERENCES archivo(id),
  nombre_archivo    VARCHAR(255) NOT NULL,
  fecha_importacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  total_filas       INTEGER NOT NULL DEFAULT 0,
  filas_ok          INTEGER NOT NULL DEFAULT 0,
  filas_error       INTEGER NOT NULL DEFAULT 0,
  estado            VARCHAR(20) NOT NULL,
  creado_por        VARCHAR(120) NOT NULL,
  creado_en         TIMESTAMPTZ  NOT NULL DEFAULT now(),
  modificado_por    VARCHAR(120),
  modificado_en     TIMESTAMPTZ,
  CONSTRAINT ck_import_estado CHECK (estado IN ('PROCESADA','PARCIAL','RECHAZADA'))
);
