CREATE TABLE propuesta_facturacion (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id        BIGINT NOT NULL REFERENCES empresa(id),
  cliente_id        BIGINT NOT NULL REFERENCES cliente(id),
  proyecto_id       BIGINT REFERENCES proyecto(id),
  importacion_id    BIGINT REFERENCES importacion_csv(id),
  factura_id        BIGINT REFERENCES factura(id),
  origen            VARCHAR(15) NOT NULL,
  periodo_anio      SMALLINT    NOT NULL,
  periodo_mes       SMALLINT    NOT NULL,
  fecha_facturacion DATE        NOT NULL,
  descripcion       VARCHAR(300) NOT NULL,
  -- Snapshot inmutable del cálculo
  moneda_origen     VARCHAR(3)    NOT NULL,
  precio_base_neto  NUMERIC(18,4) NOT NULL,
  acuerdo_id        BIGINT REFERENCES acuerdo_precio(id),
  acuerdo_tipo      VARCHAR(25),
  acuerdo_valor     NUMERIC(18,4),
  acuerdo_moneda    VARCHAR(3),
  valor_uf          NUMERIC(12,4),
  fecha_valor_uf    DATE,
  neto_clp          NUMERIC(18,0) NOT NULL,
  tasa_iva          NUMERIC(6,4)  NOT NULL,
  iva_clp           NUMERIC(18,0) NOT NULL,
  total_clp         NUMERIC(18,0) NOT NULL,
  estado            VARCHAR(15) NOT NULL DEFAULT 'PENDIENTE',
  creado_por        VARCHAR(120) NOT NULL,
  creado_en         TIMESTAMPTZ  NOT NULL DEFAULT now(),
  modificado_por    VARCHAR(120),
  modificado_en     TIMESTAMPTZ,
  CONSTRAINT ck_prop_origen CHECK (origen IN ('CICLO','CSV')),
  CONSTRAINT ck_prop_moneda CHECK (moneda_origen IN ('UF','CLP')),
  CONSTRAINT ck_prop_mes    CHECK (periodo_mes BETWEEN 1 AND 12),
  CONSTRAINT ck_prop_estado CHECK (estado IN ('PENDIENTE','PENDIENTE_UF','FACTURADA','ANULADA')),
  CONSTRAINT ck_prop_facturada CHECK (estado <> 'FACTURADA' OR factura_id IS NOT NULL)
);

-- Idempotencia del ciclo: un proyecto no puede tener dos propuestas de ciclo
-- para el mismo período (año-mes). No aplica a las de origen CSV.
CREATE UNIQUE INDEX uq_prop_ciclo_periodo
  ON propuesta_facturacion (proyecto_id, periodo_anio, periodo_mes)
  WHERE origen = 'CICLO';

CREATE INDEX ix_prop_periodo ON propuesta_facturacion (empresa_id, periodo_anio, periodo_mes);
CREATE INDEX ix_prop_cliente ON propuesta_facturacion (cliente_id);
CREATE INDEX ix_prop_estado  ON propuesta_facturacion (empresa_id, estado);
CREATE INDEX ix_prop_factura ON propuesta_facturacion (factura_id);
