CREATE TABLE ejecucion_ciclo (
  id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id             BIGINT NOT NULL REFERENCES empresa(id),
  periodo_anio           SMALLINT NOT NULL,
  periodo_mes            SMALLINT NOT NULL,
  ejecutado_en           TIMESTAMPTZ NOT NULL DEFAULT now(),
  disparo                VARCHAR(15) NOT NULL,
  cantidad_generadas     INTEGER NOT NULL DEFAULT 0,
  cantidad_pendientes_uf INTEGER NOT NULL DEFAULT 0,
  estado                 VARCHAR(20) NOT NULL,
  observacion            VARCHAR(500),
  ejecutado_por          VARCHAR(120) NOT NULL,
  CONSTRAINT ck_ejec_disparo CHECK (disparo IN ('AUTOMATICO','MANUAL')),
  CONSTRAINT ck_ejec_estado  CHECK (estado IN ('EXITOSA','CON_ADVERTENCIAS','ERROR')),
  CONSTRAINT ck_ejec_mes     CHECK (periodo_mes BETWEEN 1 AND 12)
);
