spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NOMBRE}
    username: ${DB_USUARIO}
    password: ${DB_CLAVE}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_CLAVE:}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

logging:
  level:
    cl.helpcom.facturacion: INFO
